# -*- coding: utf-8 -*-
"""Real-Time Emotion Detection from Text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZjJAJGz0GutKUCUuEk3GZsBYj235VB8
"""

pip install transformers torch

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

# Load pre-trained model (no dataset needed)
model_name = "j-hartmann/emotion-english-distilroberta-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name)

label_names = ['anger','disgust','fear','joy','neutral','sadness','surprise']

def predict_emotion(text):
    inputs = tokenizer(text, return_tensors="pt")
    outputs = model(**inputs)
    logits = outputs.logits
    predicted_class_id = torch.argmax(logits).item()
    return label_names[predicted_class_id]

# Demo
while True:
    text = input("\nEnter a sentence (or 'q' to quit): ")
    if text.lower() == "q":
        break
    print("Emotion:", predict_emotion(text))

